# Generated by Django 5.0.6 on 2024-06-20 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('price', models.FloatField(max_length=16, verbose_name='进货价')),
                ('price2', models.FloatField(max_length=16, verbose_name='售价')),
                ('storage', models.IntegerField(default=0, verbose_name='库存量')),
                ('quality_time', models.IntegerField(default=36, verbose_name='保质期(月)')),
                ('insurance', models.IntegerField(choices=[(1, '是'), (2, '否')], verbose_name='是否纳入医保')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='供货商名')),
                ('address', models.CharField(max_length=64, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='InOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('total_price', models.IntegerField(default=0, verbose_name='总价')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.drug', verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='OutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('total_price', models.IntegerField(default=0, verbose_name='总价')),
                ('insurance', models.BooleanField(choices=[(True, '是'), (False, '否')], verbose_name='是否使用医保卡支付')),
                ('out_type', models.CharField(choices=[('sale', '售出'), ('loss', '损耗（过保质期）')], max_length=10, verbose_name='方式')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.drug', verbose_name='名称')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.supplier', verbose_name='供货商'),
        ),
    ]
