# Generated by Django 5.0.6 on 2024-06-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inorder',
            name='production_date',
            field=models.DateTimeField(default='2024-06-19 15:06:01.253898', verbose_name='生产日期'),
            preserve_default=False,
        ),
    ]
