# Generated by Django 5.0.6 on 2024-06-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_inorder_production_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('little', '库存过少'), ('time', '即将过期')], max_length=10, verbose_name='预警类型')),
                ('time', models.IntegerField(verbose_name='剩余时间')),
                ('count', models.IntegerField(verbose_name='剩余数量')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.drug', verbose_name='药品id')),
                ('in_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.inorder', verbose_name='入库id')),
            ],
        ),
    ]
