# Generated by Django 5.0.6 on 2024-06-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='count',
            field=models.IntegerField(null=True, verbose_name='剩余数量'),
        ),
        migrations.AlterField(
            model_name='warnings',
            name='drug_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.drug', verbose_name='药品id'),
        ),
        migrations.AlterField(
            model_name='warnings',
            name='in_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.inorder', verbose_name='入库id'),
        ),
        migrations.AlterField(
            model_name='warnings',
            name='time',
            field=models.IntegerField(null=True, verbose_name='剩余时间'),
        ),
    ]
