# Generated by Django 5.0.6 on 2024-06-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_warnings_count_alter_warnings_drug_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='drug_type',
            field=models.IntegerField(choices=[(1, '处方药'), (2, '非处方药'), (3, '中药'), (4, '保健品'), (5, '其他')], default=5, verbose_name='药品种类'),
            preserve_default=False,
        ),
    ]
